import type { Metadata } from "next";
import {Rubik} from "next/font/google"
import "./globals.css";
import Navbar from "../components/Navbar";

const rubik = Rubik({
  subsets:["latin"],
  weight:["400","700"]
})

export const metadata: Metadata = {
  title: "Travel with me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${rubik.className} text-white`}
    >
      <body className="w-full h-screen bg-black ">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}

